[toolchain]
channel = "nightly"
profile = "default"
components = ["rust-src"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-linux-android",

    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "aarch64-linux-android",
]
